name: Vercel Speed Insights

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  vercel-speed-insights:
    runs-on: ubuntu-latest
    steps:
      # Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configuración de Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Instalación de dependencias
      - name: Install dependencies
        run: npm install

      # Ejecución de @vercel/speed-insights
      - name: Run Vercel Speed Insights
        run: npx @vercel/speed-insights --url https://gaia-revenge.vercel.app/